# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
        - lib/*

builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
