name: fix_306
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: '>=0.41.2 <2.0.0'
  build: ^1.6.1
  build_config: ^0.4.4
  json_annotation: ^4.0.0

dependency_overrides:
  json_serializable:
    git:
      url: https://github.com/pratikpparikh/json_serializable.dart
      path: json_serializable
      ref: 6f618def53638b29db2e016771f6f941d507ce38

dev_dependencies:
  build_runner: ^1.0.0
  build_verify: ^1.1.0
  collection: ^1.14.0
  dart_style: ^1.2.0
  logging: ^1.0.0
  json_serializable:
    git:
      url: https://github.com/pratikpparikh/json_serializable.dart
      path: json_serializable
      ref: 6f618def53638b29db2e016771f6f941d507ce38
  test:

